export const MOROCCAN_CITIES_221 = [
  'Agadir',
  'Agdz',
  'Agouraï',
  'Ahfir',
  'Aïn Beni Mathar',
  'Aïn El-Aouda',
  'Aïn Erreggada',
  'Aïn Harrouda',
  'Aïn Taoujdate',
  'Aït Iaâza',
  'Aït Baha',
  'Aït Daoud',
  'Aït Melloul',
  'Aït Ourir',
  'Akka',
  'Aklim',
  'Aknoul',
  'Ajdir',
  'Al Aroui',
  'Al Hoceïma',
  'Amizmiz',
  'Aoulouz',
  'Arfoud',
  'Assa',
  'Assilah',
  'Azemmour',
  'Azilal',
  'Azrou',
  'Bejaâd',
  'Ben Ahmed',
  'Ben Guerir',
  'Ben Taïeb',
  'Béni Mellal',
  'Ben Slimane',
  'Berkane',
  'Berrechid',
  'Bhalil',
  'Biougra',
  'Bni Ansar',
  'Bni Bouayach',
  'Bni Drar',
  'Bouarfa',
  'Boudnib',
  'Bouizakarne',
  'Boujdour',
  'Boujniba',
  'Boulemane',
  'Boumalne-Dadès',
  'Bouskoura',
  'Bouznika',
  'Casablanca',
  'Chefchaouen',
  'Chichaoua',
  'Dakhla',
  'Dar Gueddari',
  'Dcheira El Jihadia',
  'Debdou',
  'Demnate',
  'Driouch',
  'Echemmaia',
  'El Aïoun Sidi Mellouk',
  'El Borouj',
  'El Gara',
  'El Hajeb',
  'El Hanchane',
  'El Jadida',
  'El Kelaâ des Sraghna',
  'El Ksiba',
  'El Mansouria',
  'El Marsa',
  'El Menzel',
  'El Ouatia',
  'Errachidia',
  'Er-Rich',
  'Essaouira',
  'Es-Semara',
  'Fam El Hisn',
  'Figuig',
  'Fnideq',
  'Foum Zguid',
  'Fkih Ben Salah',
  'Ghafsaï',
  'Goulmima',
  'Guelmim',
  'Guercif',
  'Gueznaïa',
  'Had Kourt',
  'Hattane',
  'Ifrane',
  'Imintanoute',
  'Imouzzer Kandar',
  'Imouzzer Marmoucha',
  'Imzouren',
  'Inezgane',
  'Irherm',
  'Jamâat Shaim',
  'Jerada',
  'Jorf',
  'Jorf El Melha',
  "Kalaat M'Gouna",
  'Karia Ba Mohamed',
  'Kasba Tadla',
  'Kénitra',
  'Khémisset',
  'Khénifra',
  'Khouribga',
  'Ksar El Kébir',
  'Laâttaouia',
  'Laâyoune',
  'Lagouira',
  'Lakhsas',
  'Lahraouyine',
  'Larache',
  'Lakouablia',
  'Loulad',
  'Lqliâa',
  'Martil',
  "M'diq",
  'Médiouna',
  'Mechra Bel Ksiri',
  'Mehdia',
  'Midar',
  'Midelt',
  'Missour',
  'Mohammédia',
  'Moulay Ali Cherif',
  'Moulay Driss Zerhoun',
  "M'rirt",
  'Nador',
  'Naïma',
  'Nouaceur',
  'Ouarzazate',
  'Oued Amlil',
  'Oued Laou',
  'Oued Zem',
  'Ouezzane',
  'Ouislane',
  'Oujda',
  'Oulad Abbou',
  'Oulad Ayad',
  'Oulad Berhil',
  'Oulad Frej',
  'Oulad Teïma',
  'Outat El Haj',
  'Rabat',
  'Ribate El Kheir',
  'Rommani',
  'Sabaâ Aïyoun',
  'Safi',
  'Saïdia',
  'Salé',
  'Sebt Gzoula',
  'Séfrou',
  'Selouane',
  'Semara',
  'Settat',
  'Sidi Allal El Bahraoui',
  'Sidi Bennour',
  'Sidi Bou Othmane',
  'Sidi Bouknadel',
  'Sidi Kacem',
  'Sidi Hajjaj Oulad Mrah',
  'Sidi Ifni',
  'Sidi Rahhal',
  'Sidi Slimane',
  'Sidi Slimane Echcharaa',
  'Sidi Yahya El Gharb',
  'Skhirat',
  'Souk El Arbaa du Gharb',
  'Tafraout',
  'Tahannaout',
  'Tahla',
  'Talmest',
  'Taliouine',
  'Tamanar',
  'Tamellalt',
  'Tanger',
  'Tan-Tan',
  'Taounate',
  'Tarfaya',
  'Targuist',
  'Taourirt',
  'Taroudant',
  'Tata',
  'Taza',
  'Taznakht',
  'Témara',
  'Tétouan',
  'Thar Es-Souk',
  'Tiflet',
  'Tinejdad',
  'Tinghir',
  'Tissa',
  'Tit Mellil',
  'Tiznit',
  'Touissit',
  'Toulal',
  'Youssoufia',
  'Zag',
  'Zagora',
  'Zaïo',
  'Zaouïat Cheikh',
  'Zeghanghane',
  'Zemamra',
  'Afourar',
  'Aghbala',
  'Aghbalou',
  'Aguelmous',
  'Aïn Leuh',
  'Aïn Cheggag',
  'Aïn Dorij',
  'Aïn Jemaa',
  'Aïn Karma',
  'Aït Boubidmane',
  'Aït Ishaq',
  'Alnif',
  'Amalou Ighriben',
  'Aoufous',
  'Aourir',
  'Arbaoua',
  'Assahrij'
]
